const sounds = [
  {
    title: 'Brown 900',
    artist: 'v3 Tighter Slopes',
    onImage: require('../assets/images/on/water_foam.jpg'),
    offImage: require('../assets/images/off/switzerland_lake_mountains.jpg'),
    sound: 'noise_brown_v3_131_600_tighter_slopes_mini.mp3',
    // color: "#5f1ddd",
    id: '1',
    duration: 886,
  },
  {
    title: 'Brown 900',
    artist: 'LC MOD',
    // audioSrc: cali,
    // image: require('../assets/images/vista3.jpg'),
    onImage: require('../assets/images/on/clouds.jpg'),
    offImage: require('../assets/images/off/palm_tree_night_skyline.jpg'),
    sound: 'brown_900Hz_lc_noise_mod_mini.mp3',
    id: '2',
    // "https://p.scdn.co/mp3-preview/ef83054a53d976a0e5e947b39cff362a2db7c631?cid=1d62fc4c9282424c8d5611d95669ba0d",
    // color: "#ffb77a",
    duration: 732,
  },
  {
    title: 'PinkBrown',
    artist: 'LC Noise Together',
    // image: require('../assets/images/vista2.jpg'),
    onImage: require('../assets/images/on/HotAirLowerBalloonsInTheSky.jpg'),
    offImage: require('../assets/images/off/cool_beach_sunsets.jpg'),
    sound: 'pink_brown_900Hz_lc_noise_together_mini.mp3',
    // color: "#CFE3E2",
    id: '3',
    duration: 886,
  },
  {
    title: 'Brown 900',
    artist: 'LC Noise',
    onImage: require('../assets/images/on/blue_sky_field_of_wheat.jpg'),
    offImage: require('../assets/images/off/glass_water_mountain_valley.jpg'),
    sound: 'brown_900hz_lc_noise_mini.mp3',
    // color: "#5f9fff",
    id: '4',
    duration: 886,
  },
];

export default sounds;
